<?php
class Occupation
{
    public static $categories = [
        '' => '',
        'office' => '事務関連職種',
        'pro' => '専門的職種',
        'business' => '営業関連職種',
        'sales' => '販売関連職種',
        'food' => 'フード関連職種',
        'alcohol' => 'アルコール主体職種',
        'fastfood' => 'ファーストフード関連職種',
        'transport' => '運輸・物流関連職種',
        'field' => '現場作業関連職種',
        'service' => 'サービス関連職種',
        'talent' => '芸能関連職種',
        'intro' => '紹介職種',
        'temp' => '派遣職種',
        'other' => 'その他',
    ];

    public static $rows = [
        1 => ['category' => 'office', 'name' => '貿易事務'],
        2 => ['category' => 'office', 'name' => '秘書'],
        3 => ['category' => 'office', 'name' => '受付'],
        4 => ['category' => 'office', 'name' => '電話応対'],
        5 => ['category' => 'office', 'name' => '経理・財務・会計事務'],
        6 => ['category' => 'office', 'name' => '企画'],
        7 => ['category' => 'office', 'name' => '広報・宣伝'],
        8 => ['category' => 'office', 'name' => '販売促進'],
        9 => ['category' => 'office', 'name' => 'アンケート・モニター'],
        10 => ['category' => 'office', 'name' => '原稿担当・トラフィック'],
        11 => ['category' => 'office', 'name' => '手配業務'],
        12 => ['category' => 'office', 'name' => '一般事務'],
        13 => ['category' => 'office', 'name' => '派遣コーディネーター'],
        14 => ['category' => 'office', 'name' => 'ファイリング'],
        15 => ['category' => 'office', 'name' => '伝票整理'],
        16 => ['category' => 'office', 'name' => '資料作成'],
        17 => ['category' => 'office', 'name' => 'その他事務'],
        18 => ['category' => 'office', 'name' => '総務・人事・法務等内勤職種'],
        19 => ['category' => 'office', 'name' => '学校事務'],
        20 => ['category' => 'office', 'name' => '清書'],
        21 => ['category' => 'office', 'name' => '営業事務'],
        22 => ['category' => 'office', 'name' => 'ＤＭ作業'],
        23 => ['category' => 'office', 'name' => '医療事務'],
        24 => ['category' => 'pro', 'name' => 'ＣＡＤオペレーター'],
        25 => ['category' => 'pro', 'name' => '建築・設計関連技術者'],
        26 => ['category' => 'pro', 'name' => '電気・機械設計関連技術者'],
        27 => ['category' => 'pro', 'name' => '研究開発技術者'],
        28 => ['category' => 'pro', 'name' => '印刷・製本'],
        29 => ['category' => 'pro', 'name' => 'グラフィックデザイナー'],
        30 => ['category' => 'pro', 'name' => 'コピーライター'],
        31 => ['category' => 'pro', 'name' => 'イラストレイター'],
        32 => ['category' => 'pro', 'name' => '広告制作'],
        33 => ['category' => 'pro', 'name' => '編集者'],
        34 => ['category' => 'pro', 'name' => 'ライター'],
        35 => ['category' => 'pro', 'name' => '記者'],
        36 => ['category' => 'pro', 'name' => 'カメラマン（男女）'],
        37 => ['category' => 'pro', 'name' => 'アートディレクター'],
        38 => ['category' => 'pro', 'name' => '校正'],
        39 => ['category' => 'pro', 'name' => 'その他デザイナー'],
        40 => ['category' => 'pro', 'name' => 'WEBデザイナー'],
        41 => ['category' => 'pro', 'name' => 'システムアドミニストレーター'],
        42 => ['category' => 'pro', 'name' => 'ＳＥ（システムエンジニア）'],
        43 => ['category' => 'pro', 'name' => 'プログラマー'],
        44 => ['category' => 'pro', 'name' => 'その他コンピュータ関連職'],
        45 => ['category' => 'pro', 'name' => 'ネットワークエンジニア'],
        46 => ['category' => 'pro', 'name' => '財務スペシャリスト'],
        47 => ['category' => 'pro', 'name' => '金融スペシャリスト'],
        48 => ['category' => 'pro', 'name' => 'ＯＡ・ワープロオペレーター'],
        49 => ['category' => 'pro', 'name' => 'コンピュータオペレータ'],
        50 => ['category' => 'pro', 'name' => 'データ入力'],
        51 => ['category' => 'pro', 'name' => 'ＤＴＰオペレーター'],
        52 => ['category' => 'pro', 'name' => '写植・版下'],
        53 => ['category' => 'pro', 'name' => '製版・刷版・レタッチ'],
        54 => ['category' => 'pro', 'name' => 'トレーサー'],
        55 => ['category' => 'pro', 'name' => 'ファッションデザイナー'],
        56 => ['category' => 'pro', 'name' => 'パタンナー'],
        57 => ['category' => 'pro', 'name' => 'ソーイング'],
        58 => ['category' => 'pro', 'name' => 'ＣＧオペレーター'],
        59 => ['category' => 'pro', 'name' => 'インターネットコンテンツ制作'],
        60 => ['category' => 'pro', 'name' => 'ゲームテスター'],
        61 => ['category' => 'pro', 'name' => 'ゲームクリエイター'],
        62 => ['category' => 'pro', 'name' => 'インテリアデザイナー'],
        63 => ['category' => 'pro', 'name' => 'インテリアコーディネーター'],
        64 => ['category' => 'pro', 'name' => 'ディスプレイ'],
        65 => ['category' => 'pro', 'name' => 'ビデオ・ラジオ・テレビ関連技術者'],
        66 => ['category' => 'pro', 'name' => 'ポップライター'],
        67 => ['category' => 'pro', 'name' => 'レタリング'],
        68 => ['category' => 'pro', 'name' => 'アニメータ'],
        69 => ['category' => 'pro', 'name' => '漫画家・漫画家アシスタント'],
        70 => ['category' => 'pro', 'name' => 'レイアウター'],
        71 => ['category' => 'pro', 'name' => '通訳・翻訳'],
        72 => ['category' => 'pro', 'name' => 'その他専門職'],
        73 => ['category' => 'pro', 'name' => 'バイヤー・仕入れ業務'],
        74 => ['category' => 'pro', 'name' => 'マーチャンダイザー'],
        75 => ['category' => 'pro', 'name' => '管理職'],
        76 => ['category' => 'pro', 'name' => '店長・マネージャー（フード関連）'],
        77 => ['category' => 'pro', 'name' => '店長・マネジャー候補（フード関連）'],
        78 => ['category' => 'pro', 'name' => '店長・マネージャー（販売職）'],
        79 => ['category' => 'pro', 'name' => '店長・マネージャー候補（販売職）'],
        80 => ['category' => 'pro', 'name' => '店長・マネージャー（アルコール関連）'],
        81 => ['category' => 'pro', 'name' => '店長・マネージャー候補（アルコール関連）'],
        82 => ['category' => 'pro', 'name' => '店長・マネージャー（サービス業関連）'],
        83 => ['category' => 'pro', 'name' => '店長・マネージャー候補（サービス業関連）'],
        84 => ['category' => 'pro', 'name' => '店長・マネージャー（アミューズメント・レジャー関連）'],
        85 => ['category' => 'pro', 'name' => '店長・マネージャー候補（アミューズメント・レジャー関連）'],
        86 => ['category' => 'pro', 'name' => '美容師'],
        87 => ['category' => 'pro', 'name' => '理容師'],
        88 => ['category' => 'pro', 'name' => 'エステティシャン、ネイリスト'],
        89 => ['category' => 'pro', 'name' => 'スタイリスト(ファッション関連職)'],
        90 => ['category' => 'pro', 'name' => 'ヘアメイク・メイクアップアーティスト・着付けスタッフ'],
        91 => ['category' => 'pro', 'name' => 'アシスタント・中間生(美容師系)'],
        92 => ['category' => 'pro', 'name' => 'リフレクソロジスト・セラピスト'],
        93 => ['category' => 'pro', 'name' => 'その他美容師系職種'],
        94 => ['category' => 'pro', 'name' => 'まつげ施術スタッフ'],
        95 => ['category' => 'pro', 'name' => 'その他エステ・ネイリスト・リラク系職種'],
        96 => ['category' => 'pro', 'name' => '看護婦・看護士、准看護婦・准看護士'],
        97 => ['category' => 'pro', 'name' => '薬剤師'],
        98 => ['category' => 'pro', 'name' => '歯科衛生士・歯科技工士'],
        99 => ['category' => 'pro', 'name' => '歯科助手'],
        100 => ['category' => 'pro', 'name' => 'ホームヘルパー'],
        101 => ['category' => 'pro', 'name' => 'マッサージ・ハリ・灸師'],
        102 => ['category' => 'pro', 'name' => '栄養士'],
        103 => ['category' => 'pro', 'name' => '医療関係技術者'],
        104 => ['category' => 'pro', 'name' => 'その他介護スタッフ'],
        105 => ['category' => 'pro', 'name' => 'ケアマネージャー（介護支援専門員）'],
        106 => ['category' => 'pro', 'name' => '介護福祉士'],
        107 => ['category' => 'pro', 'name' => '看護助手'],
        108 => ['category' => 'pro', 'name' => '理学療法士（PT）・作業療法士（OT）・言語聴覚士（ST）'],
        109 => ['category' => 'pro', 'name' => '保健師'],
        110 => ['category' => 'pro', 'name' => '診療情報管理士・診療録管理士'],
        111 => ['category' => 'pro', 'name' => 'サービス提供責任者'],
        112 => ['category' => 'pro', 'name' => 'サービス管理責任者'],
        113 => ['category' => 'pro', 'name' => '医師'],
        114 => ['category' => 'pro', 'name' => '精神保健福祉士（PSW）'],
        115 => ['category' => 'pro', 'name' => '生活相談員'],
        116 => ['category' => 'pro', 'name' => '介護助手'],
        117 => ['category' => 'pro', 'name' => '塾講師'],
        118 => ['category' => 'pro', 'name' => '家庭教師'],
        119 => ['category' => 'pro', 'name' => '保育士'],
        120 => ['category' => 'pro', 'name' => 'インストラクター'],
        121 => ['category' => 'pro', 'name' => 'ＯＡインストラクター'],
        122 => ['category' => 'pro', 'name' => 'その他教育・人材系職種'],
        123 => ['category' => 'pro', 'name' => '幼稚園教諭'],
        124 => ['category' => 'pro', 'name' => '試験監督・試験官（教育・資格試験）'],
        125 => ['category' => 'pro', 'name' => 'プール監視員'],
        126 => ['category' => 'pro', 'name' => '保育補助'],
        127 => ['category' => 'pro', 'name' => '自動車整備士'],
        128 => ['category' => 'pro', 'name' => 'メカニック（修理・整備士）'],
        129 => ['category' => 'pro', 'name' => 'スキャナーオペレーター'],
        130 => ['category' => 'pro', 'name' => '音響関係技術者'],
        131 => ['category' => 'pro', 'name' => '飼育係'],
        132 => ['category' => 'pro', 'name' => 'その他有資格職種'],
        133 => ['category' => 'pro', 'name' => '非破壊検査エンジニア'],
        134 => ['category' => 'pro', 'name' => 'トリマー'],
        135 => ['category' => 'pro', 'name' => '造園・庭師'],
        136 => ['category' => 'business', 'name' => '企画営業'],
        137 => ['category' => 'business', 'name' => '営業'],
        138 => ['category' => 'business', 'name' => '渉外'],
        139 => ['category' => 'business', 'name' => 'セールスエンジニア'],
        140 => ['category' => 'business', 'name' => '営業・企画営業(法人対象)'],
        141 => ['category' => 'business', 'name' => '営業・企画営業(個人対象)'],
        142 => ['category' => 'business', 'name' => 'テレフォンアポインター'],
        143 => ['category' => 'business', 'name' => '営業アシスタント'],
        144 => ['category' => 'business', 'name' => 'ルートセールス'],
        145 => ['category' => 'business', 'name' => '専業'],
        146 => ['category' => 'business', 'name' => 'その他営業関連職'],
        147 => ['category' => 'business', 'name' => 'チラシ・パンフレット配布'],
        148 => ['category' => 'business', 'name' => '集金業務'],
        149 => ['category' => 'sales', 'name' => 'ファッションアドバイザー'],
        150 => ['category' => 'sales', 'name' => 'レジ'],
        151 => ['category' => 'sales', 'name' => 'デモンストレーター'],
        152 => ['category' => 'sales', 'name' => 'ＣＶＳスタッフ（業務全般）'],
        153 => ['category' => 'sales', 'name' => 'ＤＰＥスタッフ（業務全般）'],
        154 => ['category' => 'sales', 'name' => 'ＣＤ・ビデオレンタルスタッフ（業務全般）'],
        155 => ['category' => 'sales', 'name' => '販売（コスメ関連）'],
        156 => ['category' => 'sales', 'name' => '家電・携帯販売'],
        157 => ['category' => 'sales', 'name' => '雑貨・生活小物販売'],
        158 => ['category' => 'sales', 'name' => 'ＣＤ・ビデオ販売スタッフ'],
        159 => ['category' => 'sales', 'name' => '書籍販売'],
        160 => ['category' => 'sales', 'name' => 'その他販売'],
        161 => ['category' => 'sales', 'name' => '陳列・在庫管理'],
        162 => ['category' => 'sales', 'name' => 'ペットショップスタッフ'],
        163 => ['category' => 'sales', 'name' => 'スーパー店舗スタッフ'],
        164 => ['category' => 'sales', 'name' => '花屋スタッフ'],
        165 => ['category' => 'sales', 'name' => '100円ショップスタッフ'],
        166 => ['category' => 'sales', 'name' => 'ホームセンタースタッフ'],
        167 => ['category' => 'sales', 'name' => 'イベント関連グッズ販売スタッフ'],
        168 => ['category' => 'sales', 'name' => 'カーディーラー（販売）'],
        169 => ['category' => 'sales', 'name' => '登録販売者'],
        170 => ['category' => 'sales', 'name' => 'お中元・お歳暮関係'],
        171 => ['category' => 'food', 'name' => 'フードデリバリー'],
        172 => ['category' => 'food', 'name' => '食品製造・販売　　　　'],
        173 => ['category' => 'food', 'name' => '居酒屋キッチンスタッフ'],
        174 => ['category' => 'food', 'name' => 'カフェキッチンスタッフ'],
        175 => ['category' => 'food', 'name' => 'レストランキッチンスタッフ'],
        176 => ['category' => 'food', 'name' => 'その他飲食店キッチンスタッフ'],
        177 => ['category' => 'food', 'name' => 'パン製造スタッフ'],
        178 => ['category' => 'food', 'name' => 'ケーキ製造スタッフ'],
        179 => ['category' => 'food', 'name' => '焼肉屋キッチンスタッフ'],
        180 => ['category' => 'food', 'name' => 'うどん・蕎麦屋キッチンスタッフ'],
        181 => ['category' => 'food', 'name' => '寿司屋キッチンスタッフ'],
        182 => ['category' => 'food', 'name' => 'ラーメン屋キッチンスタッフ'],
        183 => ['category' => 'food', 'name' => 'ビアガーデンキッチンスタッフ'],
        184 => ['category' => 'food', 'name' => '弁当屋（調理）'],
        185 => ['category' => 'food', 'name' => '惣菜（調理）'],
        186 => ['category' => 'food', 'name' => '居酒屋ホールスタッフ'],
        187 => ['category' => 'food', 'name' => 'カフェホールスタッフ'],
        188 => ['category' => 'food', 'name' => 'レストランホールスタッフ'],
        189 => ['category' => 'food', 'name' => 'その他飲食店ホールスタッフ'],
        190 => ['category' => 'food', 'name' => '焼肉屋ホールスタッフ'],
        191 => ['category' => 'food', 'name' => 'うどん・蕎麦屋ホールスタッフ'],
        192 => ['category' => 'food', 'name' => '寿司屋ホールスタッフ'],
        193 => ['category' => 'food', 'name' => 'ラーメン屋ホールスタッフ'],
        194 => ['category' => 'food', 'name' => 'ビアガーデンホールスタッフ'],
        195 => ['category' => 'food', 'name' => '弁当屋（販売）'],
        196 => ['category' => 'food', 'name' => '惣菜（販売）'],
        197 => ['category' => 'food', 'name' => '洗い場・パントリー'],
        198 => ['category' => 'food', 'name' => 'その他フード職種'],
        199 => ['category' => 'food', 'name' => 'ピザ屋スタッフ（デリバリー含む）'],
        200 => ['category' => 'food', 'name' => 'フードコート内スタッフ'],
        201 => ['category' => 'alcohol', 'name' => 'フロアレディ'],
        202 => ['category' => 'alcohol', 'name' => 'カウンターレディ'],
        203 => ['category' => 'alcohol', 'name' => 'ママ・チーママ'],
        204 => ['category' => 'alcohol', 'name' => 'バニーガール'],
        205 => ['category' => 'alcohol', 'name' => 'バーテン'],
        206 => ['category' => 'alcohol', 'name' => 'カウンター・その他スタッフ（飲食業）'],
        207 => ['category' => 'alcohol', 'name' => 'ホールスタッフ（アルコール）'],
        208 => ['category' => 'fastfood', 'name' => 'ファーストフード店内業務全般'],
        209 => ['category' => 'transport', 'name' => '牛乳・新聞配達'],
        210 => ['category' => 'transport', 'name' => '在庫管理・商品管理'],
        211 => ['category' => 'transport', 'name' => '構内作業オペレーター（フォークリフト等）'],
        212 => ['category' => 'transport', 'name' => '構内作業スタッフ'],
        213 => ['category' => 'transport', 'name' => '商品梱包'],
        214 => ['category' => 'transport', 'name' => '品出し・ピッキング'],
        215 => ['category' => 'transport', 'name' => '引越しスタッフ'],
        216 => ['category' => 'transport', 'name' => 'セールスドライバー'],
        217 => ['category' => 'transport', 'name' => '配達・配送'],
        218 => ['category' => 'transport', 'name' => 'バイク便'],
        219 => ['category' => 'transport', 'name' => 'ルートサービス'],
        220 => ['category' => 'transport', 'name' => 'ドライバー助手'],
        221 => ['category' => 'transport', 'name' => 'ドライバー'],
        222 => ['category' => 'transport', 'name' => '大型ドライバー'],
        223 => ['category' => 'transport', 'name' => '普通ドライバー'],
        224 => ['category' => 'transport', 'name' => 'けん引ドライバー'],
        225 => ['category' => 'transport', 'name' => 'バスドライバー'],
        226 => ['category' => 'transport', 'name' => '中型ドライバー'],
        227 => ['category' => 'transport', 'name' => '運転手'],
        228 => ['category' => 'transport', 'name' => '発送・仕分け作業'],
        229 => ['category' => 'transport', 'name' => 'その他運輸・発送'],
        230 => ['category' => 'field', 'name' => '農林水産業従事者'],
        231 => ['category' => 'field', 'name' => '測量技士'],
        232 => ['category' => 'field', 'name' => '土木工事関連職'],
        233 => ['category' => 'field', 'name' => '躯体工事関連職'],
        234 => ['category' => 'field', 'name' => '仕上工事関連職'],
        235 => ['category' => 'field', 'name' => '設備工事関連職'],
        236 => ['category' => 'field', 'name' => '製造（重工業除く）'],
        237 => ['category' => 'field', 'name' => '金属・非鉄金属関連製造'],
        238 => ['category' => 'field', 'name' => '機械・電気関連製造'],
        239 => ['category' => 'field', 'name' => '自動車・輸送用機械製造'],
        240 => ['category' => 'field', 'name' => '調査'],
        241 => ['category' => 'field', 'name' => '遺跡発掘調査'],
        242 => ['category' => 'field', 'name' => '自然環境調査'],
        243 => ['category' => 'field', 'name' => '清掃'],
        244 => ['category' => 'field', 'name' => '洗浄・クリーニング'],
        245 => ['category' => 'field', 'name' => 'ビルメンテナンス'],
        246 => ['category' => 'field', 'name' => '保守・検査・点検（ビル等）'],
        247 => ['category' => 'field', 'name' => '建築・土木現場監督'],
        248 => ['category' => 'field', 'name' => '生産管理'],
        249 => ['category' => 'field', 'name' => 'メンテナンス（ビル除く）'],
        250 => ['category' => 'field', 'name' => '設備施工管理・現場監督'],
        251 => ['category' => 'field', 'name' => '品質管理'],
        252 => ['category' => 'field', 'name' => '組立・加工'],
        253 => ['category' => 'field', 'name' => '消毒業務・害虫駆除'],
        254 => ['category' => 'service', 'name' => 'コールセンタースタッフ'],
        255 => ['category' => 'service', 'name' => 'ガソリンスタンドスタッフ'],
        256 => ['category' => 'service', 'name' => 'フロント（スポーツ・レジャー関連）'],
        257 => ['category' => 'service', 'name' => '冠婚葬祭関係職種'],
        258 => ['category' => 'service', 'name' => 'ユーザーサポート（コンピュータ関連）'],
        259 => ['category' => 'service', 'name' => 'イベントスタッフ'],
        260 => ['category' => 'service', 'name' => 'キャンペーンスタッフ'],
        261 => ['category' => 'service', 'name' => 'コンパニオン・ナレーターコンパニオン'],
        262 => ['category' => 'service', 'name' => 'その他サービス業関連職種'],
        263 => ['category' => 'service', 'name' => 'カラオケボックススタッフ（業務全般）'],
        264 => ['category' => 'service', 'name' => 'レジャー施設内業務全般'],
        265 => ['category' => 'service', 'name' => '漫画喫茶スタッフ'],
        266 => ['category' => 'service', 'name' => '映画館スタッフ'],
        267 => ['category' => 'service', 'name' => '温泉・銭湯スタッフ（業務全般）'],
        268 => ['category' => 'service', 'name' => 'スキー場スタッフ'],
        269 => ['category' => 'service', 'name' => 'レンタカースタッフ'],
        270 => ['category' => 'service', 'name' => 'ホールスタッフ（パチンコ関連）'],
        271 => ['category' => 'service', 'name' => 'ホールスタッフ（アミューズメント関連）'],
        272 => ['category' => 'service', 'name' => 'ツアーコンダクター'],
        273 => ['category' => 'service', 'name' => '案内係・クローク'],
        274 => ['category' => 'service', 'name' => 'ベルボーイ（男女）'],
        275 => ['category' => 'service', 'name' => 'ベッドメイキング'],
        276 => ['category' => 'service', 'name' => 'ペンション業務'],
        277 => ['category' => 'service', 'name' => '旅館業務'],
        278 => ['category' => 'service', 'name' => '民宿業務'],
        279 => ['category' => 'service', 'name' => '客室係'],
        280 => ['category' => 'service', 'name' => 'フロント（宿泊施設）'],
        281 => ['category' => 'service', 'name' => 'その他宿泊施設業務'],
        282 => ['category' => 'service', 'name' => 'その他旅行系職種'],
        283 => ['category' => 'service', 'name' => '警備員'],
        284 => ['category' => 'service', 'name' => '監視員'],
        285 => ['category' => 'service', 'name' => 'お手伝いさん'],
        286 => ['category' => 'service', 'name' => 'ベビーシッター'],
        287 => ['category' => 'service', 'name' => 'キャディ'],
        288 => ['category' => 'service', 'name' => 'エレベーター係'],
        289 => ['category' => 'service', 'name' => '管理人'],
        290 => ['category' => 'service', 'name' => 'パーキングスタッフ'],
        291 => ['category' => 'service', 'name' => 'サンプリング・ティッシュ配り'],
        292 => ['category' => 'service', 'name' => '家事代行サービススタッフ'],
        293 => ['category' => 'service', 'name' => '洗車スタッフ'],
        294 => ['category' => 'talent', 'name' => 'モデル'],
        295 => ['category' => 'talent', 'name' => 'エキストラ'],
        296 => ['category' => 'talent', 'name' => 'ミュージシャン'],
        297 => ['category' => 'talent', 'name' => '劇団員'],
        298 => ['category' => 'talent', 'name' => '俳優'],
        299 => ['category' => 'talent', 'name' => 'ダンサー'],
        300 => ['category' => 'talent', 'name' => 'マネージャー（芸能関連）'],
        301 => ['category' => 'talent', 'name' => 'その他芸能関連職種'],
        302 => ['category' => 'talent', 'name' => 'ＤＪ'],
        303 => ['category' => 'talent', 'name' => '司会'],
        304 => ['category' => 'talent', 'name' => '大・小道具'],
        305 => ['category' => 'intro', 'name' => '配膳人'],
        306 => ['category' => 'intro', 'name' => 'マネキン'],
        307 => ['category' => 'temp', 'name' => '情報機器専門派遣職'],
        308 => ['category' => 'temp', 'name' => '事務関連派遣職'],
        309 => ['category' => 'temp', 'name' => 'その他専門的派遣職'],
        310 => ['category' => 'temp', 'name' => 'サービス関連派遣職'],
        311 => ['category' => 'temp', 'name' => '営業関連派遣職'],
        312 => ['category' => 'temp', 'name' => 'その他派遣職種'],
        313 => ['category' => 'other', 'name' => '委託代理店（FC、代理店）'],
        314 => ['category' => 'other', 'name' => 'ボランティア'],
        999 => ['category' => 'other', 'name' => 'その他'],
    ];

    public static function categoryCode($id)
    {
        if (isset(self::$rows[$id])) {
            return self::$rows[$id]['category'];
        } else {
            return null;
        }
    }

    public static function find($categoryCode)
    {
        $rows = ['' => ''];
        foreach (self::$rows as $key => $val) {
            if ($val['category'] == $categoryCode) {
                $rows[$key] = $val['name'];
            }
        }
        return $rows;
    }
}
