<?php

class Trouble
{
	public static $trouble = [
        ['id' => 'afternoon', 'category' => 'way', 'adminname' => '夕方からの仕事', 'pubname' => '夕方からの仕事', 'webtokuname' => '夕方からの仕事(※TWN転載用)'],
        ['id' => 'choice', 'category' => 'way', 'adminname' => '時間や曜日が選べる・シフト自由', 'pubname' => 'シフト相談', 'webtokuname' => '時間や曜日が選べる・シフト自由'],
        ['id' => 'fixedtime', 'category' => 'way', 'adminname' => '時間固定シフト制', 'pubname' => '時間帯固定', 'webtokuname' => '時間固定シフト制'],
        ['id' => 'friend', 'category' => 'way', 'adminname' => '友達と応募OK', 'pubname' => '友達と応募OK', 'webtokuname' => '友達と応募OK'],
        ['id' => 'fulltime', 'category' => 'way', 'adminname' => 'フルタイム歓迎', 'pubname' => 'フルタイム歓迎', 'webtokuname' => 'フルタイム歓迎'],
        ['id' => 'long', 'category' => 'way', 'adminname' => '長期歓迎', 'pubname' => '長期歓迎OK', 'webtokuname' => '長期歓迎(※TWN転載用)'],
        ['id' => 'morning', 'category' => 'way', 'adminname' => '早朝・朝の仕事', 'pubname' => '早朝・午前中の仕事', 'webtokuname' => '早朝・朝の仕事(※TWN転載用)'],
        ['id' => 'night', 'category' => 'way', 'adminname' => '深夜・夜勤の仕事', 'pubname' => '深夜・夜勤の仕事', 'webtokuname' => '深夜・夜勤の仕事(※TWN転載用)'],
        ['id' => 'noon', 'category' => 'way', 'adminname' => '昼からの仕事', 'pubname' => '昼間の仕事', 'webtokuname' => '昼からの仕事(※TWN転載用)'],
        ['id' => 'now', 'category' => 'way', 'adminname' => '即日勤務OK', 'pubname' => '即日勤務OK', 'webtokuname' => '即日勤務OK'],
        ['id' => 'shiftsys', 'category' => 'way', 'adminname' => 'シフト制', 'pubname' => 'シフト制', 'webtokuname' => 'シフト制'],
        ['id' => 'short', 'category' => 'way', 'adminname' => '短期', 'pubname' => '短期OK', 'webtokuname' => '短期(※TWN転載用)'],
        ['id' => 'shorttime', 'category' => 'way', 'adminname' => '短時間勤務(1日4h以内)', 'pubname' => '短時間シフト', 'webtokuname' => '短時間勤務(1日4h以内)'],
        ['id' => 'tempstaff', 'category' => 'way', 'adminname' => '無期雇用派遣', 'pubname' => '無期雇用派遣', 'webtokuname' => '無期雇用派遣'],
        ['id' => 'week1', 'category' => 'way', 'adminname' => '週1日からOK', 'pubname' => '週1日からOK', 'webtokuname' => '週1日からOK(※TWN転載用)'],
        ['id' => 'week2', 'category' => 'way', 'adminname' => '週2、3日からOK', 'pubname' => '週2、3日からOK', 'webtokuname' => '週2、3日からOK(※TWN転載用)'],
        ['id' => 'week4', 'category' => 'way', 'adminname' => '週4日以上OK', 'pubname' => '週4日以上OK', 'webtokuname' => '週4日以上OK(※TWN転載用)'],
        ['id' => 'weekday', 'category' => 'way', 'adminname' => '平日のみOK', 'pubname' => '平日のみ', 'webtokuname' => '平日のみOK'],
        ['id' => 'weekend', 'category' => 'way', 'adminname' => '土日祝のみOK', 'pubname' => '土日祝日のみ', 'webtokuname' => '土日祝のみOK'],
        ['id' => 'onday', 'category' => 'way', 'adminname' => '単発・1日OK', 'pubname' => null, 'webtokuname' => '単発・1日OK(※TWN転載用)'],
        ['id' => 'vacation', 'category' => 'way', 'adminname' => '春・夏・冬休み期間限定', 'pubname' => null, 'webtokuname' => '春・夏・冬休み期間限定'],
        ['id' => 'evening', 'category' => 'way', 'adminname' => '夜からの仕事', 'pubname' => null, 'webtokuname' => '夜からの仕事(※TWN転載用)'],
        ['id' => 'earns', 'category' => 'payment', 'adminname' => '高収入・高額', 'pubname' => '高収入', 'webtokuname' => '高収入・高額'],
        ['id' => 'money', 'category' => 'payment', 'adminname' => '入社祝い金支給', 'pubname' => '入社祝い金支給', 'webtokuname' => '入社祝い金支給'],
        ['id' => 'support', 'category' => 'payment', 'adminname' => '扶養内勤務OK', 'pubname' => '扶養内勤務OK', 'webtokuname' => '扶養内勤務OK'],
        ['id' => 'transportation', 'category' => 'payment', 'adminname' => '交通費支給', 'pubname' => '交通費支給', 'webtokuname' => '交通費支給'],
        ['id' => 'weekly', 'category' => 'payment', 'adminname' => '週払い', 'pubname' => '週払い', 'webtokuname' => '週払い'],
        ['id' => 'daily', 'category' => 'payment', 'adminname' => '日払い', 'pubname' => null, 'webtokuname' => '日払い'],
        ['id' => 'prepay', 'category' => 'payment', 'adminname' => '給与前払いOK', 'pubname' => null, 'webtokuname' => '給与前払いOK'],
        ['id' => 'school', 'category' => 'target', 'adminname' => '高校生応援', 'pubname' => '高校生可', 'webtokuname' => '高校生応援'],
        ['id' => 'college', 'category' => 'target', 'adminname' => '大学生歓迎', 'pubname' => '大学生歓迎', 'webtokuname' => '大学生歓迎'],
        ['id' => 'housewife', 'category' => 'target', 'adminname' => '主婦･主夫歓迎', 'pubname' => '主婦･主夫歓迎', 'webtokuname' => '主婦･主夫歓迎'],
        ['id' => 'beginner', 'category' => 'target', 'adminname' => '未経験・初心者OK', 'pubname' => '初心者OK', 'webtokuname' => '未経験・初心者OK'],
        ['id' => 'skillful', 'category' => 'target', 'adminname' => '経験者・有資格者歓迎', 'pubname' => '経験者・有資格者歓迎', 'webtokuname' => '経験者・有資格者歓迎'],
        ['id' => 'doublework', 'category' => 'target', 'adminname' => '副業・WワークOK', 'pubname' => '掛け持ちOK', 'webtokuname' => '副業・WワークOK'],
        ['id' => 'middle', 'category' => 'target', 'adminname' => 'ミドル活躍中', 'pubname' => 'ミドル活躍中', 'webtokuname' => 'ミドル活躍中'],
        ['id' => 'senior', 'category' => 'target', 'adminname' => 'シニア応援', 'pubname' => 'シニア応援', 'webtokuname' => 'シニア応援'],
        ['id' => 'education', 'category' => 'target', 'adminname' => '学歴不問', 'pubname' => '学歴不問', 'webtokuname' => '学歴不問'],
        ['id' => 'international', 'category' => 'target', 'adminname' => '留学生歓迎', 'pubname' => '留学生OK', 'webtokuname' => '留学生歓迎'],
        ['id' => 'free', 'category' => 'target', 'adminname' => 'フリーター歓迎', 'pubname' => 'フリーター歓迎', 'webtokuname' => 'フリーター歓迎'],
        ['id' => 'blank', 'category' => 'target', 'adminname' => 'ブランクOK', 'pubname' => 'ブランクOK', 'webtokuname' => 'ブランクOK'],
        ['id' => 'no_licenses', 'category' => 'target', 'adminname' => '運転免許なしOK', 'pubname' => '運転免許なしOK', 'webtokuname' => null],
        ['id' => 'female', 'category' => 'target', 'adminname' => '女性活躍中', 'pubname' => '女性活躍中', 'webtokuname' => null],
        ['id' => 'openning', 'category' => 'environment', 'adminname' => 'オープニングスタッフ', 'pubname' => 'オープニングスタッフ', 'webtokuname' => 'オープニングスタッフ'],
        ['id' => 'car', 'category' => 'environment', 'adminname' => '車通勤OK', 'pubname' => '車通勤OK', 'webtokuname' => '車通勤OK'],
        ['id' => 'bike', 'category' => 'environment', 'adminname' => 'バイク通勤OK', 'pubname' => 'バイク通勤OK', 'webtokuname' => 'バイク通勤OK'],
        ['id' => 'uniform', 'category' => 'environment', 'adminname' => '制服あり', 'pubname' => '制服あり', 'webtokuname' => '制服あり'],
        ['id' => 'child', 'category' => 'environment', 'adminname' => '託児所あり', 'pubname' => '託児所あり', 'webtokuname' => '託児所あり'],
        ['id' => 'nearstation', 'category' => 'environment', 'adminname' => '駅チカ･駅ナカ', 'pubname' => '駅チカ･駅ナカ', 'webtokuname' => '駅チカ･駅ナカ'],
        ['id' => 'overtime', 'category' => 'environment', 'adminname' => '残業なし', 'pubname' => '残業なし', 'webtokuname' => '残業なし'],
        ['id' => 'training', 'category' => 'environment', 'adminname' => '研修あり', 'pubname' => '研修あり', 'webtokuname' => '研修あり'],
        ['id' => 'self', 'category' => 'environment', 'adminname' => 'セルフSS希望', 'pubname' => 'セルフスタンド希望', 'webtokuname' => null],
        ['id' => 'full', 'category' => 'environment', 'adminname' => 'フルサービスSS希望', 'pubname' => 'フルサービススタンド希望', 'webtokuname' => null],
        ['id' => 'hair', 'category' => 'environment', 'adminname' => '髪型・髪色自由', 'pubname' => null, 'webtokuname' => '髪型・髪色自由'],
        ['id' => 'english', 'category' => 'environment', 'adminname' => '英語が活かせる', 'pubname' => null, 'webtokuname' => '英語が活かせる'],
        ['id' => 'fashion', 'category' => 'environment', 'adminname' => '服装自由', 'pubname' => null, 'webtokuname' => '服装自由'],
        ['id' => 'resort', 'category' => 'environment', 'adminname' => 'リゾート', 'pubname' => null, 'webtokuname' => 'リゾート(※TWN転載用)'],
        ['id' => 'homework', 'category' => 'environment', 'adminname' => '在宅', 'pubname' => null, 'webtokuname' => '在宅'],
        ['id' => 'nail', 'category' => 'environment', 'adminname' => '髭・ネイル・ピアスOK', 'pubname' => null, 'webtokuname' => '髭・ネイル・ピアスOK'],
        ['id' => 'food', 'category' => 'treatment', 'adminname' => 'まかない・食事補助あり', 'pubname' => 'まかない・食事補助あり', 'webtokuname' => 'まかない・食事補助あり'],
        ['id' => 'house', 'category' => 'treatment', 'adminname' => '寮・社宅・住宅手当あり', 'pubname' => '寮・社宅・住宅手当あり', 'webtokuname' => '寮・社宅・住宅手当あり'],
        ['id' => 'license', 'category' => 'treatment', 'adminname' => '資格取得支援制度', 'pubname' => '資格取得支援制度', 'webtokuname' => '資格取得支援制度'],
        ['id' => 'employment', 'category' => 'treatment', 'adminname' => '社員登用あり', 'pubname' => '社員登用あり', 'webtokuname' => '社員登用あり'],
        ['id' => 'discount', 'category' => 'treatment', 'adminname' => '社割あり', 'pubname' => '社割あり', 'webtokuname' => '社割あり'],
        ['id' => 'bonus', 'category' => 'treatment', 'adminname' => 'ボーナス・賞与あり', 'pubname' => null, 'webtokuname' => 'ボーナス・賞与あり'],
        ['id' => 'shuttle', 'category' => 'treatment', 'adminname' => '送迎あり', 'pubname' => null, 'webtokuname' => '送迎あり'],
        ['id' => 'maternity', 'category' => 'treatment', 'adminname' => '産休・育休制度実績あり', 'pubname' => null, 'webtokuname' => '産休・育休制度実績あり'],
        ['id' => 'longvacation', 'category' => 'treatment', 'adminname' => '長期休暇あり', 'pubname' => null, 'webtokuname' => '長期休暇あり'],
        ['id' => 'resume', 'category' => 'treatment', 'adminname' => '履歴書不要', 'pubname' => null, 'webtokuname' => '履歴書不要'],
	];

    public static $categories = [
        'way' => '働き方で探す',
        'payment' => 'お金で探す',
        'target' => '〇〇な人募集で探す',
        'environment' => '職場環境から探す',
        'treatment' => '待遇から探す',
    ];
}
