ALTER TABLE `job`
ADD COLUMN `is_hidden` TINYINT NOT NULL DEFAULT 0;
ALTER TABLE `m_media`
ADD COLUMN `is_hidden` TINYINT NOT NULL DEFAULT 0;
ALTER TABLE `m_partner`
ADD COLUMN `is_hidden` TINYINT NOT NULL DEFAULT 0;
ALTER TABLE `m_ss`
ADD COLUMN `is_hidden` TINYINT NOT NULL DEFAULT 0;
